export const animalList = [
    {
        "name": "Dog",
        "wiki_page": "https://en.wikipedia.org/wiki/Dog",
        "fun_fact": "Man's best freind",
        "home": ["on farms", "in cities"],
        "food": ["Meat", "Plants"],
        "alt_name": "Dog",
        "group": "Mammal",
        "colors": ["Brown", "Black", "White", "Gray", ],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Barks"
    },
    {
        "name": "Parrot",
        "wiki_page": "https://en.wikipedia.org/wiki/Parrot",
        "fun_fact": "Can mimic human voices and sounds",
        "home": ["in jungles", "in forests"],
        "food": ["Plants", "Nectar"],
        "alt_name": "Parrot",
        "group": "Bird",
        "colors": ["Green", "Red", "Blue"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Squawks"
    },
    {
        "name": "Ant",
        "wiki_page": "https://en.wikipedia.org/wiki/Ant",
        "fun_fact": "Can carry 50 times its own weight",
        "home": ["in deserts", "in forests", "in grasslands", "in cities"],
        "food": ["Plants", "Meat"],
        "alt_name": "Ant",
        "group": "Invertebrate",
        "colors": ["Black", "Brown"],
        "size": "Very Tiny",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Octopus",
        "wiki_page": "https://en.wikipedia.org/wiki/Octopus",
        "fun_fact": "Has 9 brains and 3 hearts",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Octopus",
        "group": "Invertebrate",
        "colors": ["Red", "Brown", "Blue"],
        "size": "Medium",
        "movement": "8 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Camel",
        "wiki_page": "https://en.wikipedia.org/wiki/Camel",
        "fun_fact": "Has two rows of long, thick eyelashes and three eyelids",
        "home": ["in deserts"],
        "food": ["Plants"],
        "alt_name": "Camel",
        "group": "Mammal",
        "colors": ["Brown", "Tan"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Raven",
        "wiki_page": "https://en.wikipedia.org/wiki/Raven",
        "fun_fact": "Can solve simple puzzles",
        "home": ["in forests", "in cities"],
        "food": ["Meat", "Plants"],
        "alt_name": "Raven",
        "group": "Bird",
        "colors": ["Black"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Caws"
    },
    {
        "name": "Bullfrog",
        "wiki_page": "https://en.wikipedia.org/wiki/American_bullfrog",
        "fun_fact": "Can jump up to 6 feet",
        "home": ["in wetlands"],
        "food": ["Meat"],
        "alt_name": "Bullfrog",
        "group": "Amphibian",
        "colors": ["Green", "Brown"],
        "size": "Tiny",
        "movement": "4 Legs",
        "sound": "Croaks"
    },
    {
        "name": "Turkey",
        "wiki_page": "https://en.wikipedia.org/wiki/Turkey_(bird)",
        "fun_fact": "Was almost the national symbol of United States",
        "home": ["in grasslands", "in forests"],
        "food": ["Plants", "Meat"],
        "alt_name": "Turkey",
        "group": "Bird",
        "colors": ["Brown", "Black"],
        "size": "Medium",
        "movement": "2 Legs",
        "sound": "Gobbles"
    },
    {
        "name": "Crocodile",
        "wiki_page": "https://en.wikipedia.org/wiki/Crocodile",
        "fun_fact": "Has the strongest bite force in the animal kingdom",
        "home": ["in wetlands", "in jungles"],
        "food": ["Meat"],
        "alt_name": "Crocodile",
        "group": "Reptile",
        "colors": ["Green", "Brown"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Blue Whale",
        "wiki_page": "https://en.wikipedia.org/wiki/Blue_whale",
        "fun_fact": "Largest animal on earth",
        "home": ["in oceans"],
        "food": ["Meat", "Plankton"],
        "alt_name": "Blue Whale",
        "group": "Mammal",
        "colors": ["Blue", "Gray"],
        "size": "Giant",
        "movement": "Fins",
        "sound": "Sings"
    },
    {
        "name": "Seagull",
        "wiki_page": "https://en.wikipedia.org/wiki/Gull",
        "fun_fact": "Can drink saltwater and spit out the salt",
        "home": ["in wetlands", "in oceans"],
        "food": ["Meat", "Plants"],
        "alt_name": "Seagull",
        "group": "Bird",
        "colors": ["White", "Gray"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Squawks"
    },
    {
        "name": "Wolf",
        "wiki_page": "https://en.wikipedia.org/wiki/Wolf",
        "fun_fact": "Lives in a pack with a leader",
        "home": ["in forests", "on mountains"],
        "food": ["Meat"],
        "alt_name": "Wolf",
        "group": "Mammal",
        "colors": ["Gray", "White"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Howls"
    },
    {
        "name": "Hummingbird",
        "wiki_page": "https://en.wikipedia.org/wiki/Hummingbird",
        "fun_fact": "The only bird that can fly backwards",
        "home": ["in jungles", "in forests"],
        "food": ["Nectar"],
        "alt_name": "Hummingbird",
        "group": "Bird",
        "colors": ["Green", "Red"],
        "size": "Tiny",
        "movement": "Wings",
        "sound": "Hums"
    },
    {
        "name": "Buffalo",
        "wiki_page": "https://en.wikipedia.org/wiki/African_bison",
        "fun_fact": "Can weigh as much as a small car",
        "home": ["in grasslands", "in wetlandss", "in forests"],
        "food": ["Plants"],
        "alt_name": "Buffalo",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Huge",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Chicken",
        "wiki_page": "https://en.wikipedia.org/wiki/Chicken",
        "fun_fact": "Lays eggs almost every day",
        "home": ["on farms", "in jungles"],
        "food": ["Plants", "Meat"],
        "alt_name": "Chicken",
        "group": "Bird",
        "colors": ["Brown", "White"],
        "size": "Small",
        "movement": "2 Legs",
        "sound": "Clucks"
    },
    {
        "name": "Owl",
        "wiki_page": "https://en.wikipedia.org/wiki/Owl",
        "fun_fact": "Can turn its head almost all the way around",
        "home": ["in forests", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Owl",
        "group": "Bird",
        "colors": ["Brown", "White"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Hoots"
    },
    {
        "name": "Giraffe",
        "wiki_page": "https://en.wikipedia.org/wiki/Giraffe",
        "fun_fact": "Tallest animal, can reach treetops",
        "home": ["in grasslands"],
        "food": ["Plants"],
        "alt_name": "Giraffe",
        "group": "Mammal",
        "colors": ["Brown", "Yellow"],
        "size": "Giant",
        "movement": "4 Legs",
        "sound": "Hums"
    },
    {
        "name": "Goldfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Goldfish",
        "fun_fact": "Does not have a stomach",
        "home": ["in oceans", "in cities"],
        "food": ["Plants", "Meat + Plants"],
        "alt_name": "Goldfish",
        "group": "Fish",
        "colors": ["Orange", "Yellow"],
        "size": "Tiny",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Koala",
        "wiki_page": "https://en.wikipedia.org/wiki/Koala",
        "fun_fact": "Sleeps up to 18 hours a day",
        "home": ["in forests"],
        "food": ["Plants"],
        "alt_name": "Koala",
        "group": "Mammal",
        "colors": ["Gray"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Rat",
        "wiki_page": "https://en.wikipedia.org/wiki/Rat",
        "fun_fact": "A surprisingly social and smart rodent",
        "home": ["in cities", "in forests"],
        "food": ["Meat", "Plants"],
        "alt_name": "Rat",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Squeaks"
    },
    {
        "name": "Zebra",
        "wiki_page": "https://en.wikipedia.org/wiki/Zebra",
        "fun_fact": "Stripes are unique like fingerprints",
        "home": ["in grasslands"],
        "food": ["Plants"],
        "alt_name": "Zebra",
        "group": "Mammal",
        "colors": ["Black", "White"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Barks"
    },
    {
        "name": "Jaguar",
        "wiki_page": "https://en.wikipedia.org/wiki/Jaguar",
        "fun_fact": "Hunts and kills crocodiles",
        "home": ["in jungles", "in forests"],
        "food": ["Meat"],
        "alt_name": "Jaguar",
        "group": "Mammal",
        "colors": ["Yellow", "Black", "White", "Spotted"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Roars"
    },
    {
        "name": "Common Starfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Common_Starfish",
        "fun_fact": "Can regrow its arms if they break",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Sea Star",
        "group": "Invertebrate",
        "colors": ["Red", "Orange"],
        "size": "Tiny",
        "movement": "5 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Cheetah",
        "wiki_page": "https://en.wikipedia.org/wiki/Cheetah",
        "fun_fact": "Fastest land animal, runs up to 60 mph",
        "home": ["in grasslands"],
        "food": ["Meat"],
        "alt_name": "Cheetah",
        "group": "Mammal",
        "colors": ["Yellow", "Black", "Spotted"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Purrs"
    },
    {
        "name": "Great White Shark",
        "wiki_page": "https://en.wikipedia.org/wiki/Great_white_shark",
        "fun_fact": "Has over 300 teeth in rows",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Great White Shark",
        "group": "Fish",
        "colors": ["Gray", "White"],
        "size": "Huge",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Red Fox",
        "wiki_page": "https://en.wikipedia.org/wiki/Red_fox",
        "fun_fact": "One of the few canines that does not hunt packs",
        "home": ["in forests", "in grasslands"],
        "food": ["Meat", "Plants"],
        "alt_name": "Red Fox",
        "group": "Mammal",
        "colors": ["Red", "White", "Brown"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Barks"
    },
    {
        "name": "Lizard",
        "wiki_page": "https://en.wikipedia.org/wiki/Lizard",
        "fun_fact": "Some can drop their tail and regrow them",
        "home": ["in deserts", "in jungles"],
        "food": ["Meat", "Plants"],
        "alt_name": "Lizard",
        "group": "Reptile",
        "colors": ["Green", "Brown"],
        "size": "Tiny",
        "movement": "4 Legs",
        "sound": "Squeaks"
    },
    {
        "name": "Cow",
        "wiki_page": "https://en.wikipedia.org/wiki/Cattle",
        "fun_fact": "Has four stomachs to digest food",
        "home": ["on farms", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Cow",
        "group": "Mammal",
        "colors": ["Brown", "White", "Black"],
        "size": "Huge",
        "movement": "4 Legs",
        "sound": "Moos"
    },
    {
        "name": "Hamster",
        "wiki_page": "https://en.wikipedia.org/wiki/Hamster",
        "fun_fact": "Despite their cute appearance, they are very terretorial in the wild",
        "home": ["in cities", "in grasslands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Hamster",
        "group": "Mammal",
        "colors": ["Brown", "White", "Black"],
        "size": "Tiny",
        "movement": "4 Legs",
        "sound": "Squeaks"
    },
    {
        "name": "Bear",
        "wiki_page": "https://en.wikipedia.org/wiki/Bear",
        "fun_fact": "Some hibernate all winter",
        "home": ["in forests", "on mountains"],
        "food": ["Meat", "Plants"],
        "alt_name": "Bear",
        "group": "Mammal",
        "colors": ["Brown", "Black", "White"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Growls"
    },
    {
        "name": "Tortoise",
        "wiki_page": "https://en.wikipedia.org/wiki/Tortoise",
        "fun_fact": "Can live over 100 years",
        "home": ["in deserts", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Tortoise",
        "group": "Reptile",
        "colors": ["Brown", "Green"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Guinea Pig",
        "wiki_page": "https://en.wikipedia.org/wiki/Guinea_pig",
        "fun_fact": "Wild populations are found in small herds in the Andes Mountains",
        "home": ["in cities", "on mountains", "in grasslands", "in deserts"],
        "food": ["Plants"],
        "alt_name": "Guinea Pig",
        "group": "Mammal",
        "colors": ["Brown", "White"],
        "size": "Tiny",
        "movement": "4 Legs",
        "sound": "Squeaks"
    },
    {
        "name": "Lobster",
        "wiki_page": "https://en.wikipedia.org/wiki/Lobster",
        "fun_fact": "Never stop growing",
        "home": ["in oceans"],
        "food": ["Meat", "Plants"],
        "alt_name": "Lobster",
        "group": "Invertebrate",
        "colors": ["Red", "Green"],
        "size": "Medium",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Sheep",
        "wiki_page": "https://en.wikipedia.org/wiki/Sheep",
        "fun_fact": "Gives wool for clothes",
        "home": ["on farms", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Sheep",
        "group": "Mammal",
        "colors": ["White", "Brown", "Black"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Baa"
    },
    {
        "name": "Penguin",
        "wiki_page": "https://en.wikipedia.org/wiki/Penguin",
        "fun_fact": "Slides on its belly to move fast",
        "home": ["in oceans", "in snowy areas"],
        "food": ["Meat"],
        "alt_name": "Penguin",
        "group": "Bird",
        "colors": ["Black", "White"],
        "size": "Small",
        "movement": "2 Legs",
        "sound": "Honks"
    },
    {
        "name": "Peacock",
        "wiki_page": "https://en.wikipedia.org/wiki/Peafowl",
        "fun_fact": "Shows off colorful tail to attract mates",
        "home": ["in grasslands", "in forests"],
        "food": ["Plants", "Meat"],
        "alt_name": "Peacock",
        "group": "Bird",
        "colors": ["Blue", "Green"],
        "size": "Medium",
        "movement": "2 Legs",
        "sound": "Screams"
    },
    {
        "name": "Squirrel",
        "wiki_page": "https://en.wikipedia.org/wiki/Squirrel",
        "fun_fact": "Stores its food in the ground",
        "home": ["in forests", "in cities"],
        "food": ["Plants"],
        "alt_name": "Squirrel",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Tiny",
        "movement": "4 Legs",
        "sound": "Chirps"
    },
    {
        "name": "Pig",
        "wiki_page": "https://en.wikipedia.org/wiki/Pig",
        "fun_fact": "Loves to roll in mud to stay cool",
        "home": ["on farms", "in forests"],
        "food": ["Meat", "Plants"],
        "alt_name": "Pig",
        "group": "Mammal",
        "colors": ["Pink", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Oinks"
    },
    {
        "name": "Orca",
        "wiki_page": "https://en.wikipedia.org/wiki/Orca",
        "fun_fact": "Hunts in groups called pods",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Killer Whale",
        "group": "Mammal",
        "colors": ["Black", "White"],
        "size": "Huge",
        "movement": "Fins",
        "sound": "Whistles"
    },
    {
        "name": "Raccoon",
        "wiki_page": "https://en.wikipedia.org/wiki/Raccoon",
        "fun_fact": "Can unscrew jars",
        "home": ["in forests", "in cities"],
        "food": ["Meat", "Plants"],
        "alt_name": "Raccoon",
        "group": "Mammal",
        "colors": ["Gray", "Black"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Chitters"
    },
    {
        "name": "Crab",
        "wiki_page": "https://en.wikipedia.org/wiki/Crab",
        "fun_fact": "Walks sideways to move",
        "home": ["in oceans", "in wetlands"],
        "food": ["Meat", "Plants"],
        "alt_name": "Crab",
        "group": "Invertebrate",
        "colors": ["Red", "Brown"],
        "size": "Small",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Elephant",
        "wiki_page": "https://en.wikipedia.org/wiki/Elephant",
        "fun_fact": "Uses their noses for breathing, drinking, and grasping",
        "home": ["in grasslands", "in jungles"],
        "food": ["Plants"],
        "alt_name": "Elephant",
        "group": "Mammal",
        "colors": ["Gray"],
        "size": "Giant",
        "movement": "4 Legs",
        "sound": "Trumpets"
    },
    {
        "name": "Otter",
        "wiki_page": "https://en.wikipedia.org/wiki/Otter",
        "fun_fact": "Uses rocks to crack open shells",
        "home": ["in wetlands", "in oceans"],
        "food": ["Meat"],
        "alt_name": "Otter",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Whistles"
    },
    {
        "name": "Clownfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Clownfish",
        "fun_fact": "Lives safely among stinging anemones",
        "home": ["in oceans"],
        "food": ["Meat", "Plants"],
        "alt_name": "Clownfish",
        "group": "Fish",
        "colors": ["Orange", "Black"],
        "size": "Tiny",
        "movement": "Fins",
        "sound": "Quiet"
    },
        {
        "name": "Goat",
        "wiki_page": "https://en.wikipedia.org/wiki/Goat",
        "fun_fact": "Can climb steep on mountainss with ease",
        "home": ["on farms", "on mountains"],
        "food": ["Plants"],
        "alt_name": "Goat",
        "group": "Mammal",
        "colors": ["Brown", "White", "Black"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Bleats"
    },
    {
        "name": "Grasshopper",
        "wiki_page": "https://en.wikipedia.org/wiki/Grasshopper",
        "fun_fact": "Can jump 20 times its body length",
        "home": ["in grasslands", "in forests"],
        "food": ["Plants"],
        "alt_name": "Grasshopper",
        "group": "Invertebrate",
        "colors": ["Green", "Brown"],
        "size": "Tiny",
        "movement": "5-6 Legs",
        "sound": "Chirps"
    },
    {
        "name": "Swan",
        "wiki_page": "https://en.wikipedia.org/wiki/Swan",
        "fun_fact": "Mates with one partner for life",
        "home": ["in wetlands"],
        "food": ["Plants"],
        "alt_name": "Swan",
        "group": "Bird",
        "colors": ["White", "Black"],
        "size": "Medium",
        "movement": "2 Legs",
        "sound": "Honks"
    },
    {
        "name": "Tiger",
        "wiki_page": "https://en.wikipedia.org/wiki/Tiger",
        "fun_fact": "Has stripes that help it hide in tall grass",
        "home": ["in jungles", "in forests"],
        "food": ["Meat"],
        "alt_name": "Tiger",
        "group": "Mammal",
        "colors": ["Orange", "Black"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Roars"
    },
    {
        "name": "Gorilla",
        "wiki_page": "https://en.wikipedia.org/wiki/Gorilla",
        "fun_fact": "Lives in family groups led by a silverback",
        "home": ["in jungles", "in forests"],
        "food": ["Plants"],
        "alt_name": "Gorilla",
        "group": "Mammal",
        "colors": ["Black", "Gray"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Sloth",
        "wiki_page": "https://en.wikipedia.org/wiki/Sloth",
        "fun_fact": "Moves so slowly algae grows on its fur",
        "home": ["in jungles", "in forests"],
        "food": ["Plants"],
        "alt_name": "Sloth",
        "group": "Mammal",
        "colors": ["Brown", "Green"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Cat",
        "wiki_page": "https://en.wikipedia.org/wiki/Cat",
        "fun_fact": "Can jump five times its own height",
        "home": ["in cities", "on farms"],
        "food": ["Meat"],
        "alt_name": "Cat",
        "group": "Mammal",
        "colors": ["Brown", "Black", "White"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Meows"
    },
    {
        "name": "Mouse",
        "wiki_page": "https://en.wikipedia.org/wiki/Mouse",
        "fun_fact": "Can fit through a hole the size of a pencil",
        "home": ["in cities", "in forests", "in grasslands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Mouse",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Tiny",
        "movement": "4 Legs",
        "sound": "Squeaks"
    },
    {
        "name": "Ostrich",
        "wiki_page": "https://en.wikipedia.org/wiki/Ostrich",
        "fun_fact": "Fastest bird on land, runs up to 45 mph",
        "home": ["in grasslands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Ostrich",
        "group": "Bird",
        "colors": ["Brown", "White"],
        "size": "Big",
        "movement": "2 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Hawk",
        "wiki_page": "https://en.wikipedia.org/wiki/Hawk",
        "fun_fact": "Has super sharp eyesight to spot prey",
        "home": ["in forests", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Hawk",
        "group": "Bird",
        "colors": ["Brown", "White"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Screams"
    },
    {
        "name": "Dolphin",
        "wiki_page": "https://en.wikipedia.org/wiki/Dolphin",
        "fun_fact": "Uses clicks and whistles to talk",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Dolphin",
        "group": "Mammal",
        "colors": ["Gray", "Blue"],
        "size": "Big",
        "movement": "Fins",
        "sound": "Whistles"
    },
    {
        "name": "Eagle",
        "wiki_page": "https://en.wikipedia.org/wiki/Eagle",
        "fun_fact": "Can see fish from a mile away",
        "home": ["on mountains", "in forests"],
        "food": ["Meat"],
        "alt_name": "Eagle",
        "group": "Bird",
        "colors": ["Brown", "White"],
        "size": "Medium",
        "movement": "Wings",
        "sound": "Screeches"
    },
    {
        "name": "Turtle",
        "wiki_page": "https://en.wikipedia.org/wiki/Turtle",
        "fun_fact": "Carries its home on its back",
        "home": ["in wetlands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Turtle",
        "group": "Reptile",
        "colors": ["Green", "Brown"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Panda",
        "wiki_page": "https://en.wikipedia.org/wiki/Panda",
        "fun_fact": "Eats for 12 hours a day",
        "home": ["in forests", "on mountains"],
        "food": ["Plants"],
        "alt_name": "Panda",
        "group": "Mammal",
        "colors": ["Black", "White"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Bleats"
    },
    {
        "name": "Moose",
        "wiki_page": "https://en.wikipedia.org/wiki/Moose",
        "fun_fact": "Has antlers as wide as a car",
        "home": ["in forests", "in wetlands"],
        "food": ["Plants"],
        "alt_name": "Moose",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Huge",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Chimpanzee",
        "wiki_page": "https://en.wikipedia.org/wiki/Chimpanzee",
        "fun_fact": "Known to use tools to get food",
        "home": ["in jungles", "in forests"],
        "food": ["Plants", "Meat"],
        "alt_name": "Chimpanzee",
        "group": "Mammal",
        "colors": ["Black", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Screams"
    },
    {
        "name": "Flamingo",
        "wiki_page": "https://en.wikipedia.org/wiki/Flamingo",
        "fun_fact": "Gets their pink color from the food they eat",
        "home": ["in wetlands"],
        "food": ["Plankton"],
        "alt_name": "Flamingo",
        "group": "Bird",
        "colors": ["Pink"],
        "size": "Medium",
        "movement": "2 Legs",
        "sound": "Honks"
    },
    {
        "name": "Duck",
        "wiki_page": "https://en.wikipedia.org/wiki/Duck",
        "fun_fact": "Has waterproof feathers",
        "home": ["in wetlands", "on farms"],
        "food": ["Plants", "Meat"],
        "alt_name": "Duck",
        "group": "Bird",
        "colors": ["Brown", "Green"],
        "size": "Small",
        "movement": "2 Legs",
        "sound": "Quacks"
    },
    {
        "name": "Woodpecker",
        "wiki_page": "https://en.wikipedia.org/wiki/Woodpecker",
        "fun_fact": "Pecks trees to find bugs",
        "home": ["in forests"],
        "food": ["Meat"],
        "alt_name": "Woodpecker",
        "group": "Bird",
        "colors": ["Black", "Red"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Drums"
    },
    {
        "name": "Donkey",
        "wiki_page": "https://en.wikipedia.org/wiki/Donkey",
        "fun_fact": "Can carry heavy loads for miles",
        "home": ["on farms", "in deserts"],
        "food": ["Plants"],
        "alt_name": "Donkey",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Brays"
    },
    {
        "name": "Rhinocerous",
        "wiki_page": "https://en.wikipedia.org/wiki/Rhinoceros",
        "fun_fact": "Has a horn made of hair",
        "home": ["in grasslands"],
        "food": ["Plants"],
        "alt_name": "Rhinoceros",
        "group": "Mammal",
        "colors": ["Gray"],
        "size": "Huge",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Leopard",
        "wiki_page": "https://en.wikipedia.org/wiki/Leopard",
        "fun_fact": "An agile hunter that climbs trees after their prey",
        "home": ["in jungles", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Leopard",
        "group": "Mammal",
        "colors": ["Yellow", "Black", "Spotted"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Roars"
    },
    {
        "name": "Butterfly",
        "wiki_page": "https://en.wikipedia.org/wiki/Butterfly",
        "fun_fact": "Tastes food with its feet",
        "home": ["in forests", "in grasslands"],
        "food": ["Nectar"],
        "alt_name": "Butterfly",
        "group": "Invertebrate",
        "colors": ["Blue", "Orange"],
        "size": "Tiny",
        "movement": "Wings",
        "sound": "Quiet"
    },
    {
        "name": "Jellyfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Jellyfish",
        "fun_fact": "Can sting with its tentacles",
        "home": ["in oceans"],
        "food": ["Plankton", "Meat"],
        "alt_name": "Jellyfish",
        "group": "Invertebrate",
        "colors": ["Pink", "Blue", "Clear"],
        "size": "Small",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Sparrow",
        "wiki_page": "https://en.wikipedia.org/wiki/Sparrow",
        "fun_fact": "Can be seen in the skies of every contentient except Antarctica",
        "home": ["in cities", "in grasslands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Sparrow",
        "group": "Bird",
        "colors": ["Brown", "Gray"],
        "size": "Tiny",
        "movement": "Wings",
        "sound": "Chirps"
    },
    {
        "name": "Monkey",
        "wiki_page": "https://en.wikipedia.org/wiki/Monkey",
        "fun_fact": "Swings from branch to branch",
        "home": ["in jungles", "in forests"],
        "food": ["Plants", "Meat"],
        "alt_name": "Monkey",
        "group": "Mammal",
        "colors": ["Brown", "Black"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Chitters"
    },
    {
        "name": "Rabbit",
        "wiki_page": "https://en.wikipedia.org/wiki/Rabbit",
        "fun_fact": "Can rotate their ears almost all the way around",
        "home": ["in grasslands", "in forests"],
        "food": ["Plants"],
        "alt_name": "Rabbit",
        "group": "Mammal",
        "colors": ["Brown", "White"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Hippopotamus",
        "wiki_page": "https://en.wikipedia.org/wiki/Hippopotamus",
        "fun_fact": "Spends most of its day in water",
        "home": ["in wetlands", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Hippopotamus",
        "group": "Mammal",
        "colors": ["Gray"],
        "size": "Huge",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Beaver",
        "wiki_page": "https://en.wikipedia.org/wiki/Beaver",
        "fun_fact": "Builds dams with sticks and mud",
        "home": ["in forests", "in wetlands"],
        "food": ["Plants"],
        "alt_name": "Beaver",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Lion",
        "wiki_page": "https://en.wikipedia.org/wiki/Lion",
        "fun_fact": "Roar can be heard 5 miles away",
        "home": ["in grasslands", "in jungles"],
        "food": ["Meat"],
        "alt_name": "Lion",
        "group": "Mammal",
        "colors": ["Brown", "Tan"],
        "size": "Huge",
        "movement": "4 Legs",
        "sound": "Roars"
    },
    {
        "name": "Crow",
        "wiki_page": "https://en.wikipedia.org/wiki/Crow",
        "fun_fact": "Can recognize human faces",
        "home": ["in forests", "in cities"],
        "food": ["Plants", "Meat"],
        "alt_name": "Crow",
        "group": "Bird",
        "colors": ["Black"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Caws"
    },
    {
        "name": "Snake",
        "wiki_page": "https://en.wikipedia.org/wiki/Snake",
        "fun_fact": "Sheds its skin to grow",
        "home": ["in deserts", "in jungles", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Snake",
        "group": "Reptile",
        "colors": ["Green", "Brown", "Black", "Gray"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Horse",
        "wiki_page": "https://en.wikipedia.org/wiki/Horse",
        "fun_fact": "Can run up to 40 miles per hour",
        "home": ["on farms", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Horse",
        "group": "Mammal",
        "colors": ["Brown", "White", "Black"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Neighs"
    },
    {
        "name": "Coyote",
        "wiki_page": "https://en.wikipedia.org/wiki/Coyote",
        "fun_fact": "Can howl to talk to its pack",
        "home": ["in grasslands", "in deserts"],
        "food": ["Meat", "Plants"],
        "alt_name": "Coyote",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Howls"
    },
    {
        "name": "Goose",
        "wiki_page": "https://en.wikipedia.org/wiki/Goose",
        "fun_fact": "Flies in a V shape to save energy",
        "home": ["in wetlands", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Goose",
        "group": "Bird",
        "colors": ["Gray", "White"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Honks"
    },
    {
        "name": "Pigeon",
        "wiki_page": "https://en.wikipedia.org/wiki/Pigeon",
        "fun_fact": "Were once used as message carriers",
        "home": ["in cities", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Pigeon",
        "group": "Bird",
        "colors": ["Gray", "White"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Coos"
    },
    {
        "name": "Polar Bear",
        "wiki_page": "https://en.wikipedia.org/wiki/Polar_bear",
        "fun_fact": "Swims long distances in icy water",
        "home": ["in snowy areas"],
        "food": ["Meat"],
        "alt_name": "Polar Bear",
        "group": "Mammal",
        "colors": ["White"],
        "size": "Huge",
        "movement": "4 Legs",
        "sound": "Growls"
    },
    {
        "name": "Bee",
        "wiki_page": "https://en.wikipedia.org/wiki/Bee",
        "fun_fact": "Makes honey in a hive",
        "home": ["in forests", "in grasslands"],
        "food": ["Nectar"],
        "alt_name": "Bee",
        "group": "Invertebrate",
        "colors": ["Yellow", "Black"],
        "size": "Very Tiny",
        "movement": "Wings",
        "sound": "Buzzes"
    },
    {
        "name": "Ladybug",
        "wiki_page": "https://en.wikipedia.org/wiki/Ladybug",
        "fun_fact": "Eats tiny bugs to help plants",
        "home": ["in forests", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Ladybug",
        "group": "Invertebrate",
        "colors": ["Red", "Black"],
        "size": "Very Tiny",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Spider",
        "wiki_page": "https://en.wikipedia.org/wiki/Spider",
        "fun_fact": "Spins webs to catch food",
        "home": ["in forests", "in cities"],
        "food": ["Meat"],
        "alt_name": "Spider",
        "group": "Invertebrate",
        "colors": ["Black", "Brown"],
        "size": "Tiny",
        "movement": "8 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Deer",
        "wiki_page": "https://en.wikipedia.org/wiki/Deer",
        "fun_fact": "Grows new antlers every year",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Deer",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Kangaroo",
        "wiki_page": "https://en.wikipedia.org/wiki/Kangaroo",
        "fun_fact": "Carries babies in a pouch",
        "home": ["in grasslands"],
        "food": ["Plants"],
        "alt_name": "Kangaroo",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Big",
        "movement": "2 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Anaconda",
        "wiki_page": "https://en.wikipedia.org/wiki/Anaconda",
        "fun_fact": "One of the longest snakes in the world",
        "home": ["in jungles", "in wetlands"],
        "food": ["Meat"],
        "alt_name": "Anaconda",
        "group": "Reptile",
        "colors": ["Green", "Brown"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Platypus",
        "wiki_page": "https://en.wikipedia.org/wiki/Platypus",
        "fun_fact": "Lays eggs but is a mammal",
        "home": ["in wetlands"],
        "food": ["Meat"],
        "alt_name": "Platypus",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Growls"
    },
    {
        "name": "Arctic Fox",
        "wiki_page": "https://en.wikipedia.org/wiki/Arctic_fox",
        "fun_fact": "Changes fur color with seasons",
        "home": ["in snowy areas"],
        "food": ["Meat"],
        "alt_name": "Arctic Fox",
        "group": "Mammal",
        "colors": ["White", "Gray"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Barks"
    },
    {
        "name": "Pelican",
        "wiki_page": "https://en.wikipedia.org/wiki/Pelican",
        "fun_fact": "Has a big pouch to scoop fish",
        "home": ["in oceans", "in wetlands"],
        "food": ["Meat"],
        "alt_name": "Pelican",
        "group": "Bird",
        "colors": ["White", "Brown"],
        "size": "Medium",
        "movement": "Wings",
        "sound": "Grunts"
    },
    {
        "name": "Komodo Dragon",
        "wiki_page": "https://en.wikipedia.org/wiki/Komodo_dragon",
        "fun_fact": "Largest lizard in the world",
        "home": ["in jungles", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Komodo Dragon",
        "group": "Reptile",
        "colors": ["Gray", "Brown"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Flea",
        "wiki_page": "https://en.wikipedia.org/wiki/Flea",
        "fun_fact": "Can jump 200 times its body length",
        "home": ["in cities", "in deserts", "in forests", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Flea",
        "group": "Invertebrate",
        "colors": ["Brown"],
        "size": "Very Tiny",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Stink Bug",
        "wiki_page": "https://en.wikipedia.org/wiki/Pentatomidae",
        "fun_fact": "Releases a bad smell to scare enemies",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Stink Bug",
        "group": "Invertebrate",
        "colors": ["Green", "Brown"],
        "size": "Very Tiny",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Hyena",
        "wiki_page": "https://en.wikipedia.org/wiki/Hyena",
        "fun_fact": "Has a laugh-like call",
        "home": ["in grasslands"],
        "food": ["Meat"],
        "alt_name": "Hyena",
        "group": "Mammal",
        "colors": ["Brown", "Black", "Spotted"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Laughs"
    },
    {
        "name": "Narwhal",
        "wiki_page": "https://en.wikipedia.org/wiki/Narwhal",
        "fun_fact": "Has a long tusk like a unicorn",
        "home": ["in oceans", "in snowy areas"],
        "food": ["Meat"],
        "alt_name": "Narwhal",
        "group": "Mammal",
        "colors": ["Gray", "White"],
        "size": "Huge",
        "movement": "Fins",
        "sound": "Whistles"
    },
    {
        "name": "Moth",
        "wiki_page": "https://en.wikipedia.org/wiki/Moth",
        "fun_fact": "Some fly only at night",
        "home": ["in forests", "in grasslands"],
        "food": ["Nectar"],
        "alt_name": "Moth",
        "group": "Invertebrate",
        "colors": ["Brown", "Gray"],
        "size": "Very Tiny",
        "movement": "Wings",
        "sound": "Quiet"
    },
    {
        "name": "Walrus",
        "wiki_page": "https://en.wikipedia.org/wiki/Walrus",
        "fun_fact": "Uses tusks to climb onto ice",
        "home": ["in oceans", "in snowy areas"],
        "food": ["Meat"],
        "alt_name": "Walrus",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Huge",
        "movement": "Flippers",
        "sound": "Barks"
    },
    {
        "name": "Vulture",
        "wiki_page": "https://en.wikipedia.org/wiki/Vulture",
        "fun_fact": "Eats food left by other animals",
        "home": ["in grasslands", "on mountains"],
        "food": ["Meat"],
        "alt_name": "Vulture",
        "group": "Bird",
        "colors": ["Brown", "Black"],
        "size": "Medium",
        "movement": "Wings",
        "sound": "Hisses"
    },
    {
        "name": "Shrimp",
        "wiki_page": "https://en.wikipedia.org/wiki/Shrimp",
        "fun_fact": "Some can snap claws to make loud sounds",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Shrimp",
        "group": "Invertebrate",
        "colors": ["Pink", "Gray"],
        "size": "Tiny",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Hammerhead Shark",
        "wiki_page": "https://en.wikipedia.org/wiki/Hammerhead_shark",
        "fun_fact": "Has a head shaped like a mallet",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Hammerhead Shark",
        "group": "Fish",
        "colors": ["Gray", "White"],
        "size": "Huge",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Sea Lion",
        "wiki_page": "https://en.wikipedia.org/wiki/Sea_lion",
        "fun_fact": "Has external ear flaps unlike their close cousins",
        "home": ["in oceanss"],
        "food": ["Meat"],
        "alt_name": "Sea Lion",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Big",
        "movement": "Flippers",
        "sound": "Barks"
    },
    {
        "name": "Seahorse",
        "wiki_page": "https://en.wikipedia.org/wiki/Seahorse",
        "fun_fact": "Male carries the babies",
        "home": ["in oceans"],
        "food": ["Plankton", "Meat"],
        "alt_name": "Seahorse",
        "group": "Fish",
        "colors": ["Yellow", "Green"],
        "size": "Tiny",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Porcupine",
        "wiki_page": "https://en.wikipedia.org/wiki/Porcupine",
        "fun_fact": "Has sharp quills for protection",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Porcupine",
        "group": "Mammal",
        "colors": ["Brown", "Black"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Termite",
        "wiki_page": "https://en.wikipedia.org/wiki/Termite",
        "fun_fact": "Builds tall mounds like castles",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Termite - maybe",
        "group": "Invertebrate",
        "colors": ["White", "Brown"],
        "size": "Very Tiny",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Wallaby",
        "wiki_page": "https://en.wikipedia.org/wiki/Wallaby",
        "fun_fact": "Hops like a small kangaroo",
        "home": ["in grasslands", "in forests"],
        "food": ["Plants"],
        "alt_name": "Wallaby - maybe",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Medium",
        "movement": "2 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Cockatoo",
        "wiki_page": "https://en.wikipedia.org/wiki/Cockatoo",
        "fun_fact": "Has a crest that pops up",
        "home": ["in jungles", "in forests"],
        "food": ["Plants"],
        "alt_name": "Cockatoo",
        "group": "Bird",
        "colors": ["White", "Pink"],
        "size": "Medium",
        "movement": "Wings",
        "sound": "Screeches"
    },
    {
        "name": "Meerkat",
        "wiki_page": "https://en.wikipedia.org/wiki/Meerkat",
        "fun_fact": "Stands guard to watch for danger",
        "home": ["in grasslands", "in deserts"],
        "food": ["Meat"],
        "alt_name": "Meerkat",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Chirps"
    },
    {
        "name": "Catfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Catfish",
        "fun_fact": "Has whiskers to feel in murky water",
        "home": ["in wetlands", "in oceans"],
        "food": ["Meat", "Plants"],
        "alt_name": "Catfish",
        "group": "Fish",
        "colors": ["Brown", "Gray"],
        "size": "Medium",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Snail",
        "wiki_page": "https://en.wikipedia.org/wiki/Snail",
        "fun_fact": "Carries a spiral shell home",
        "home": ["in forests", "in wetlands"],
        "food": ["Plants"],
        "alt_name": "Snail",
        "group": "Invertebrate",
        "colors": ["Brown", "Gray"],
        "size": "Tiny",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Millipede",
        "wiki_page": "https://en.wikipedia.org/wiki/Millipede",
        "fun_fact": "Has hundreds of tiny legs",
        "home": ["in forests", "in jungles"],
        "food": ["Plants"],
        "alt_name": "Millipede",
        "group": "Invertebrate",
        "colors": ["Black", "Brown"],
        "size": "Tiny",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Clam",
        "wiki_page": "https://en.wikipedia.org/wiki/Clam",
        "fun_fact": "Can make pearls inside its shell",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Clam",
        "group": "Invertebrate",
        "colors": ["Gray", "White"],
        "size": "Small",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Heron",
        "wiki_page": "https://en.wikipedia.org/wiki/Heron",
        "fun_fact": "Stands still to catch fish",
        "home": ["in wetlands"],
        "food": ["Meat"],
        "alt_name": "Heron - maybe",
        "group": "Bird",
        "colors": ["Gray", "White"],
        "size": "Medium",
        "movement": "2 Legs",
        "sound": "Squawks"
    },
    {
        "name": "Alligator",
        "wiki_page": "https://en.wikipedia.org/wiki/Alligator",
        "fun_fact": "Can close its jaws with 2,000 pounds of force",
        "home": ["in wetlands", "in jungles"],
        "food": ["Meat"],
        "alt_name": "Alligator",
        "group": "Reptile",
        "colors": ["Green", "Gray"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Centipede",
        "wiki_page": "https://en.wikipedia.org/wiki/Centipede",
        "fun_fact": "Has a pair of legs for each body segment",
        "home": ["in forests", "in jungles"],
        "food": ["Meat"],
        "alt_name": "Centipede",
        "group": "Invertebrate",
        "colors": ["Brown", "Red"],
        "size": "Tiny",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Barnacle",
        "wiki_page": "https://en.wikipedia.org/wiki/Barnacle",
        "fun_fact": "Sticks to rocks and ships",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Barnacle",
        "group": "Invertebrate",
        "colors": ["White", "Gray"],
        "size": "Very Tiny",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Wildebeest",
        "wiki_page": "https://en.wikipedia.org/wiki/Wildebeest",
        "fun_fact": "Migrates in huge herds",
        "home": ["in grasslands"],
        "food": ["Plants"],
        "alt_name": "Wildebeest - maybe",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Skunk",
        "wiki_page": "https://en.wikipedia.org/wiki/Skunk",
        "fun_fact": "Sprays a smelly liquid to scare enemies",
        "home": ["in forests", "in grasslands"],
        "food": ["Meat", "Plants"],
        "alt_name": "Skunk",
        "group": "Mammal",
        "colors": ["Black", "White"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Llama",
        "wiki_page": "https://en.wikipedia.org/wiki/Llama",
        "fun_fact": "Spits when it feels threatened",
        "home": ["on farms", "on mountains"],
        "food": ["Plants"],
        "alt_name": "Llama",
        "group": "Mammal",
        "colors": ["Brown", "White"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Hums"
    },
    {
        "name": "Cicada",
        "wiki_page": "https://en.wikipedia.org/wiki/Cicada",
        "fun_fact": "Makes loud noises to attract mates",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Cicada",
        "group": "Invertebrate",
        "colors": ["Green", "Black"],
        "size": "Tiny",
        "movement": "Wings",
        "sound": "Buzzes"
    },
    {
        "name": "Stick Insect",
        "wiki_page": "https://en.wikipedia.org/wiki/Stick_insect",
        "fun_fact": "Looks like a twig to hide",
        "home": ["in forests", "in jungles"],
        "food": ["Plants"],
        "alt_name": "Stick Insect",
        "group": "Invertebrate",
        "colors": ["Green", "Brown"],
        "size": "Small",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Swordfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Swordfish",
        "fun_fact": "Has a long, sword-like nose",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Swordfish",
        "group": "Fish",
        "colors": ["Blue", "Gray"],
        "size": "Big",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Cockroach",
        "wiki_page": "https://en.wikipedia.org/wiki/Cockroach",
        "fun_fact": "Can live without its head for a week",
        "home": ["in cities", "in forests"],
        "food": ["Plants", "Meat"],
        "alt_name": "Cockroach",
        "group": "Invertebrate",
        "colors": ["Brown"],
        "size": "Tiny",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Mosquito",
        "wiki_page": "https://en.wikipedia.org/wiki/Mosquito",
        "fun_fact": "Can smell humans from far away",
        "home": ["in wetlands", "in forests"],
        "food": ["Nectar", "Meat"],
        "alt_name": "Mosquito",
        "group": "Invertebrate",
        "colors": ["Black", "Brown"],
        "size": "Very Tiny",
        "movement": "Wings",
        "sound": "Buzzes"
    },
    {
        "name": "Iguana",
        "wiki_page": "https://en.wikipedia.org/wiki/Iguana",
        "fun_fact": "Can fall from trees and survive",
        "home": ["in jungles", "in wetlands"],
        "food": ["Plants"],
        "alt_name": "Iguana",
        "group": "Reptile",
        "colors": ["Green", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Sea Turtle",
        "wiki_page": "https://en.wikipedia.org/wiki/Sea_turtle",
        "fun_fact": "Females lay their eggs at the same place they were born",
        "home": ["in oceans"],
        "food": ["Plants", "Meat"],
        "alt_name": "Sea Turtle",
        "group": "Reptile",
        "colors": ["Green", "Brown"],
        "size": "Big",
        "movement": "Flippers",
        "sound": "Quiet"
    },
    {
        "name": "Scorpion",
        "wiki_page": "https://en.wikipedia.org/wiki/Scorpion",
        "fun_fact": "Glows under special light",
        "home": ["in deserts"],
        "food": ["Meat"],
        "alt_name": "Scorpion",
        "group": "Invertebrate",
        "colors": ["Brown", "Black"],
        "size": "Small",
        "movement": "8 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Cobra",
        "wiki_page": "https://en.wikipedia.org/wiki/Cobra",
        "fun_fact": "Spreads its hood to look scary",
        "home": ["in jungles", "in deserts"],
        "food": ["Meat"],
        "alt_name": "Cobra",
        "group": "Reptile",
        "colors": ["Brown", "Black"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Eel",
        "wiki_page": "https://en.wikipedia.org/wiki/Eel",
        "fun_fact": "Can swim backwards",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Eel",
        "group": "Fish",
        "colors": ["Green", "Black"],
        "size": "Medium",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Reindeer",
        "wiki_page": "https://en.wikipedia.org/wiki/Reindeer",
        "fun_fact": "Both males and females grow antlers",
        "home": ["in snowy areas", "in forests"],
        "food": ["Plants"],
        "alt_name": "Caribou",
        "group": "Mammal",
        "colors": ["Brown", "White"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Mule",
        "wiki_page": "https://en.wikipedia.org/wiki/Mule",
        "fun_fact": "Stronger than a horse for carrying loads",
        "home": ["on farms", "on mountains"],
        "food": ["Plants"],
        "alt_name": "Mule",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Brays"
    },
    {
        "name": "Cod",
        "wiki_page": "https://en.wikipedia.org/wiki/Cod",
        "fun_fact": "Can live in very cold waters",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Cod",
        "group": "Fish",
        "colors": ["Gray", "Green"],
        "size": "Medium",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Trout",
        "wiki_page": "https://en.wikipedia.org/wiki/Trout",
        "fun_fact": "Can swim against strong currents",
        "home": ["in oceans", "in wetlands"],
        "food": ["Meat"],
        "alt_name": "Trout",
        "group": "Fish",
        "colors": ["Silver", "Green"],
        "size": "Medium",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Sardine",
        "wiki_page": "https://en.wikipedia.org/wiki/Sardine",
        "fun_fact": "Swims in huge schools for safety",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Sardine",
        "group": "Fish",
        "colors": ["Silver"],
        "size": "Tiny",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "on mountains Lion",
        "wiki_page": "https://en.wikipedia.org/wiki/Cougar",
        "fun_fact": "Can leap 40 feet in one jump",
        "home": ["on mountains", "in forests"],
        "food": ["Meat"],
        "alt_name": "on mountains Lion",
        "group": "Mammal",
        "colors": ["Brown", "Tan"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Screams"
    },
    {
        "name": "Aardvark",
        "wiki_page": "https://en.wikipedia.org/wiki/Aardvark",
        "fun_fact": "Has a long snout to sniff out ants",
        "home": ["in grasslands", "in forests"],
        "food": ["Meat"],
        "alt_name": "Aardvark - maybe",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Anemone",
        "wiki_page": "https://en.wikipedia.org/wiki/Sea_anemone",
        "fun_fact": "Looks like a plant but is an animal",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Sea Anemone",
        "group": "Invertebrate",
        "colors": ["Pink", "Green"],
        "size": "Small",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Warthog",
        "wiki_page": "https://en.wikipedia.org/wiki/Warthog",
        "fun_fact": "Has tusks to dig and fight",
        "home": ["in grasslands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Warthog",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Caterpillar",
        "wiki_page": "https://en.wikipedia.org/wiki/Caterpillar",
        "fun_fact": "Turns into a butterfly or moth",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Caterpillar",
        "group": "Invertebrate",
        "colors": ["Green", "Brown"],
        "size": "Tiny",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Dingo",
        "wiki_page": "https://en.wikipedia.org/wiki/Dingo",
        "fun_fact": "Wild dog of Australia",
        "home": ["in grasslands", "in deserts"],
        "food": ["Meat"],
        "alt_name": "Dingo - maybe",
        "group": "Mammal",
        "colors": ["Brown", "Yellow"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Howls"
    },
    {
        "name": "Salmon",
        "wiki_page": "https://en.wikipedia.org/wiki/Salmon",
        "fun_fact": "Swims upstream to lay eggs",
        "home": ["in oceans", "in wetlands"],
        "food": ["Meat"],
        "alt_name": "Salmon",
        "group": "Fish",
        "colors": ["Silver", "Pink"],
        "size": "Medium",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Horsefly",
        "wiki_page": "https://en.wikipedia.org/wiki/Horsefly",
        "fun_fact": "Has super fast wings",
        "home": ["in forests", "in wetlands"],
        "food": ["Nectar", "Meat"],
        "alt_name": "Horsefly",
        "group": "Invertebrate",
        "colors": ["Black", "Brown"],
        "size": "Very Tiny",
        "movement": "Wings",
        "sound": "Buzzes"
    },
    {
        "name": "Toad",
        "wiki_page": "https://en.wikipedia.org/wiki/Toad",
        "fun_fact": "Has bumpy skin to blend in",
        "home": ["in wetlands", "in forests"],
        "food": ["Meat"],
        "alt_name": "Toad",
        "group": "Amphibian",
        "colors": ["Brown", "Green"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Croaks"
    },
    {
        "name": "Tuna",
        "wiki_page": "https://en.wikipedia.org/wiki/Tuna",
        "fun_fact": "Can swim as fast as a car",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Tuna",
        "group": "Fish",
        "colors": ["Silver", "Blue"],
        "size": "Big",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Wombat",
        "wiki_page": "https://en.wikipedia.org/wiki/Wombat",
        "fun_fact": "Digs burrows with strong claws",
        "home": ["in grasslands", "in forests"],
        "food": ["Plants"],
        "alt_name": "Wombat - maybe",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Manta Ray",
        "wiki_page": "https://en.wikipedia.org/wiki/Manta_ray",
        "fun_fact": "Flaps wings to glide through water",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Manta Ray",
        "group": "Fish",
        "colors": ["Black", "White"],
        "size": "Huge",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Pufferfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Pufferfish",
        "fun_fact": "Puffs up like a balloon to scare enemies",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Pufferfish",
        "group": "Fish",
        "colors": ["Yellow", "Green"],
        "size": "Small",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Sand Dollar",
        "wiki_page": "https://en.wikipedia.org/wiki/Sand_dollar",
        "fun_fact": "Looks like a flat, round coin",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Sand Dollar",
        "group": "Invertebrate",
        "colors": ["Gray", "White"],
        "size": "Small",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Boa Constrictor",
        "wiki_page": "https://en.wikipedia.org/wiki/Boa_constrictor",
        "fun_fact": "Squeezes prey to catch it",
        "home": ["in jungles"],
        "food": ["Meat"],
        "alt_name": "Boa Constrictor",
        "group": "Reptile",
        "colors": ["Brown", "Green"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Parrotfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Parrotfish",
        "fun_fact": "Chews coral to make sand",
        "home": ["in oceans"],
        "food": ["Plants"],
        "alt_name": "Parrotfish - maybe",
        "group": "Fish",
        "colors": ["Blue", "Green"],
        "size": "Medium",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Manatee",
        "wiki_page": "https://en.wikipedia.org/wiki/Manatee",
        "fun_fact": "Called a sea cow because it grazes on seagrass",
        "home": ["in oceans", "in wetlands"],
        "food": ["Plants"],
        "alt_name": "Manatee",
        "group": "Mammal",
        "colors": ["Gray"],
        "size": "Huge",
        "movement": "Flippers",
        "sound": "Grunts"
    },
    {
        "name": "Rattlesnake",
        "wiki_page": "https://en.wikipedia.org/wiki/Rattlesnake",
        "fun_fact": "Shakes its tail to warn enemies",
        "home": ["in deserts", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Rattlesnake",
        "group": "Reptile",
        "colors": ["Brown", "Tan"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Rattles"
    },
    {
        "name": "Barracuda",
        "wiki_page": "https://en.wikipedia.org/wiki/Barracuda",
        "fun_fact": "Has super sharp teeth for hunting",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Barracuda",
        "group": "Fish",
        "colors": ["Silver", "Green"],
        "size": "Big",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Flying Fish",
        "wiki_page": "https://en.wikipedia.org/wiki/Flying_fish",
        "fun_fact": "Glides over water like a bird",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Flying Fish",
        "group": "Fish",
        "colors": ["Silver", "Blue"],
        "size": "Small",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Whale Shark",
        "wiki_page": "https://en.wikipedia.org/wiki/Whale_shark",
        "fun_fact": "The biggest fish but eats tiny plankton",
        "home": ["in oceans"],
        "food": ["Plankton"],
        "alt_name": "Whale Shark",
        "group": "Fish",
        "colors": ["Gray", "Spotted"],
        "size": "Giant",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Alpaca",
        "wiki_page": "https://en.wikipedia.org/wiki/Alpaca",
        "fun_fact": "Gives soft wool for sweaters",
        "home": ["on farms", "on mountains"],
        "food": ["Plants"],
        "alt_name": "Alpaca",
        "group": "Mammal",
        "colors": ["White", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Hums"
    },
    {
        "name": "Stingray",
        "wiki_page": "https://en.wikipedia.org/wiki/Stingray",
        "fun_fact": "Has a sharp tail to protect itself",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Stingray",
        "group": "Fish",
        "colors": ["Gray", "Brown"],
        "size": "Big",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Housefly",
        "wiki_page": "https://en.wikipedia.org/wiki/Housefly",
        "fun_fact": "Can walk upside down",
        "home": ["in cities", "in forests"],
        "food": ["Plants", "Meat"],
        "alt_name": "Housefly",
        "group": "Invertebrate",
        "colors": ["Black", "Gray"],
        "size": "Very Tiny",
        "movement": "Wings",
        "sound": "Buzzes"
    },
    {
        "name": "Gecko",
        "wiki_page": "https://en.wikipedia.org/wiki/Gecko",
        "fun_fact": "Can stick to walls with tiny toes",
        "home": ["in jungles", "in deserts"],
        "food": ["Meat"],
        "alt_name": "Gecko",
        "group": "Reptile",
        "colors": ["Green", "Brown"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Chirps"
    },
    {
        "name": "Betta Fish",
        "wiki_page": "https://en.wikipedia.org/wiki/Betta_fish",
        "fun_fact": "Has bright fins to show off",
        "home": ["in oceans", "in cities"],
        "food": ["Meat"],
        "alt_name": "Betta Fish",
        "group": "Fish",
        "colors": ["Blue", "Red"],
        "size": "Tiny",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Macaw",
        "wiki_page": "https://en.wikipedia.org/wiki/Macaw",
        "fun_fact": "Can crack nuts with its strong beak",
        "home": ["in jungles"],
        "food": ["Plants"],
        "alt_name": "Macaw",
        "group": "Bird",
        "colors": ["Red", "Blue"],
        "size": "Medium",
        "movement": "Wings",
        "sound": "Screeches"
    },
    {
        "name": "Opossum",
        "wiki_page": "https://en.wikipedia.org/wiki/Opossum",
        "fun_fact": "Plays dead to fool predators",
        "home": ["in forests", "in cities"],
        "food": ["Meat", "Plants"],
        "alt_name": "Opossum",
        "group": "Mammal",
        "colors": ["Gray", "White"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Gazelle",
        "wiki_page": "https://en.wikipedia.org/wiki/Gazelle",
        "fun_fact": "Can leap high to escape predators",
        "home": ["in grasslands"],
        "food": ["Plants"],
        "alt_name": "Gazelle",
        "group": "Mammal",
        "colors": ["Brown", "White"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Dragonfly",
        "wiki_page": "https://en.wikipedia.org/wiki/Dragonfly",
        "fun_fact": "Has eyes with thousands of lenses",
        "home": ["in wetlands", "in forests"],
        "food": ["Meat"],
        "alt_name": "Dragonfly",
        "group": "Invertebrate",
        "colors": ["Blue", "Green"],
        "size": "Tiny",
        "movement": "Wings",
        "sound": "Buzzes"
    },
    {
        "name": "Archerfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Archerfish",
        "fun_fact": "Shoots water to catch bugs",
        "home": ["in oceans", "in wetlands"],
        "food": ["Meat"],
        "alt_name": "Archerfish",
        "group": "Fish",
        "colors": ["Silver", "Green"],
        "size": "Small",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Badger",
        "wiki_page": "https://en.wikipedia.org/wiki/Badger",
        "fun_fact": "Digs burrows with strong claws",
        "home": ["in forests", "in grasslands"],
        "food": ["Meat", "Plants"],
        "alt_name": "Badger",
        "group": "Mammal",
        "colors": ["Black", "White"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Growls"
    },
    {
        "name": "Hedgehog",
        "wiki_page": "https://en.wikipedia.org/wiki/Hedgehog",
        "fun_fact": "Rolls into a ball to protect itself",
        "home": ["in forests", "in cities"],
        "food": ["Meat"],
        "alt_name": "Hedgehog",
        "group": "Mammal",
        "colors": ["Brown", "White"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Crane",
        "wiki_page": "https://en.wikipedia.org/wiki/Crane_(bird)",
        "fun_fact": "Dances to attract a mate",
        "home": ["in wetlands", "in grasslands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Crane",
        "group": "Bird",
        "colors": ["Gray", "White"],
        "size": "Medium",
        "movement": "2 Legs",
        "sound": "Trumpets"
    },
    {
        "name": "Poison Dart Frog",
        "wiki_page": "https://en.wikipedia.org/wiki/Poison_dart_frog",
        "fun_fact": "Has skin that can be poisonous",
        "home": ["in jungles"],
        "food": ["Meat"],
        "alt_name": "Poison Dart Frog",
        "group": "Amphibian",
        "colors": ["Red", "Blue"],
        "size": "Tiny",
        "movement": "4 Legs",
        "sound": "Chirps"
    },
    {
        "name": "Python",
        "wiki_page": "https://en.wikipedia.org/wiki/Python_(genus)",
        "fun_fact": "Can swallow prey whole",
        "home": ["in jungles", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Python",
        "group": "Reptile",
        "colors": ["Brown", "Green"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Bison",
        "wiki_page": "https://en.wikipedia.org/wiki/American_bison",
        "fun_fact": "Can charge at 35 miles per hour",
        "home": ["in grasslands", "on mountains"],
        "food": ["Plants"],
        "alt_name": "Bison",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Huge",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Chameleon",
        "wiki_page": "https://en.wikipedia.org/wiki/Chameleon",
        "fun_fact": "Changes colors to hide",
        "home": ["in jungles", "in forests"],
        "food": ["Meat"],
        "alt_name": "Chameleon",
        "group": "Reptile",
        "colors": ["Green", "Brown"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Canary",
        "wiki_page": "https://en.wikipedia.org/wiki/Canary",
        "fun_fact": "Sings beautiful songs",
        "home": ["in cities", "in forests"],
        "food": ["Plants"],
        "alt_name": "Canary",
        "group": "Bird",
        "colors": ["Yellow", "Green"],
        "size": "Tiny",
        "movement": "Wings",
        "sound": "Sings"
    },
    {
        "name": "Firefly",
        "wiki_page": "https://en.wikipedia.org/wiki/Firefly",
        "fun_fact": "Glows in the dark to signal",
        "home": ["in forests", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Firefly",
        "group": "Invertebrate",
        "colors": ["Black", "Yellow"],
        "size": "Very Tiny",
        "movement": "Wings",
        "sound": "Quiet"
    },
    {
        "name": "Cricket",
        "wiki_page": "https://en.wikipedia.org/wiki/Cricket_(insect)",
        "fun_fact": "Makes music by rubbing wings",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Cricket",
        "group": "Invertebrate",
        "colors": ["Brown", "Black"],
        "size": "Tiny",
        "movement": "5-6 Legs",
        "sound": "Chirps"
    },
    {
        "name": "Red Panda",
        "wiki_page": "https://en.wikipedia.org/wiki/Red_panda",
        "fun_fact": "Climbs trees to eat bamboo",
        "home": ["in forests", "on mountains"],
        "food": ["Plants"],
        "alt_name": "Red Panda",
        "group": "Mammal",
        "colors": ["Red", "White"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Chirps"
    },
    {
        "name": "Baboon",
        "wiki_page": "https://en.wikipedia.org/wiki/Baboon",
        "fun_fact": "Lives in big social groups",
        "home": ["in grasslands", "in forests"],
        "food": ["Plants", "Meat"],
        "alt_name": "Baboon",
        "group": "Mammal",
        "colors": ["Brown", "Gray"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Barks"
    },
    {
        "name": "Earthworm",
        "wiki_page": "https://en.wikipedia.org/wiki/Earthworm",
        "fun_fact": "Helps make soil healthy",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants"],
        "alt_name": "Earthworm",
        "group": "Invertebrate",
        "colors": ["Pink", "Brown"],
        "size": "Tiny",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Toucan",
        "wiki_page": "https://en.wikipedia.org/wiki/Toucan",
        "fun_fact": "Has a big, colorful beak",
        "home": ["in jungles"],
        "food": ["Plants"],
        "alt_name": "Toucan",
        "group": "Bird",
        "colors": ["Black", "Yellow"],
        "size": "Medium",
        "movement": "Wings",
        "sound": "Croaks"
    },
    {
        "name": "Lynx",
        "wiki_page": "https://en.wikipedia.org/wiki/Lynx",
        "fun_fact": "Has big paws for walking on snow",
        "home": ["in forests", "on mountains"],
        "food": ["Meat"],
        "alt_name": "Lynx - maybe",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Hisses"
    },
    {
        "name": "Piranha",
        "wiki_page": "https://en.wikipedia.org/wiki/Piranha",
        "fun_fact": "Has razor-sharp teeth for biting",
        "home": ["in wetlands"],
        "food": ["Meat"],
        "alt_name": "Piranha",
        "group": "Fish",
        "colors": ["Silver", "Red"],
        "size": "Small",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Emu",
        "wiki_page": "https://en.wikipedia.org/wiki/Emu",
        "fun_fact": "Second tallest bird in the world",
        "home": ["in grasslands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Emu",
        "group": "Bird",
        "colors": ["Brown"],
        "size": "Huge",
        "movement": "2 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Antelope",
        "wiki_page": "https://en.wikipedia.org/wiki/Antelope",
        "fun_fact": "Can run faster than most predators",
        "home": ["in grasslands"],
        "food": ["Plants"],
        "alt_name": "Antelope",
        "group": "Mammal",
        "colors": ["Brown", "White"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Hornet",
        "wiki_page": "https://en.wikipedia.org/wiki/Hornet",
        "fun_fact": "Builds paper-like nests",
        "home": ["in forests", "in deserts"],
        "food": ["Meat", "Nectar"],
        "alt_name": "Hornet",
        "group": "Invertebrate",
        "colors": ["Black", "Yellow"],
        "size": "Very Tiny",
        "movement": "Wings",
        "sound": "Buzzes"
    },
    {
        "name": "Lionfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Lionfish",
        "fun_fact": "Has venomous spines for protection",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Lionfish",
        "group": "Fish",
        "colors": ["Red", "White"],
        "size": "Small",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Beetle",
        "wiki_page": "https://en.wikipedia.org/wiki/Beetle",
        "fun_fact": "Some have shiny wings like jewels",
        "home": ["in forests", "in grasslands"],
        "food": ["Plants", "Meat"],
        "alt_name": "Beetle",
        "group": "Invertebrate",
        "colors": ["Black", "Green"],
        "size": "Tiny",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Seal",
        "wiki_page": "https://en.wikipedia.org/wiki/Seal_(animal)",
        "fun_fact": "Can hold its breath for up to 30 minutes",
        "home": ["in oceans", "in snowy areas"],
        "food": ["Meat"],
        "alt_name": "Seal",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Big",
        "movement": "Flippers",
        "sound": "Barks"
    },
    {
        "name": "Sea Urchin",
        "wiki_page": "https://en.wikipedia.org/wiki/Sea_urchin",
        "fun_fact": "Has spines to protect itself",
        "home": ["in oceans"],
        "food": ["Plants"],
        "alt_name": "Sea Urchin",
        "group": "Invertebrate",
        "colors": ["Purple", "Black"],
        "size": "Small",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Praying Mantis",
        "wiki_page": "https://en.wikipedia.org/wiki/Praying_mantis",
        "fun_fact": "Holds arms like it’s praying",
        "home": ["in grasslands", "in deserts"],
        "food": ["Meat"],
        "alt_name": "Praying Mantis",
        "group": "Invertebrate",
        "colors": ["Green", "Brown"],
        "size": "Small",
        "movement": "5-6 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Puffin",
        "wiki_page": "https://en.wikipedia.org/wiki/Puffin",
        "fun_fact": "Dives deep to catch fish",
        "home": ["in oceans", "in snowy areas"],
        "food": ["Meat"],
        "alt_name": "Puffin",
        "group": "Bird",
        "colors": ["Black", "White"],
        "size": "Small",
        "movement": "Wings",
        "sound": "Grunts"
    },
    {
        "name": "Lemur",
        "wiki_page": "https://en.wikipedia.org/wiki/Lemur",
        "fun_fact": "Found only in Madagascar and the Comoro Islands",
        "home": ["in jungles", "in forests"],
        "food": ["Plants", "Meat"],
        "alt_name": "Lemur",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Chirps"
    },
    {
        "name": "Slug",
        "wiki_page": "https://en.wikipedia.org/wiki/Slug",
        "fun_fact": "Leaves a slimy trail to move",
        "home": ["in forests", "in wetlands"],
        "food": ["Plants"],
        "alt_name": "Slug",
        "group": "Invertebrate",
        "colors": ["Brown", "Gray"],
        "size": "Tiny",
        "movement": "10+ Legs",
        "sound": "Quiet"
    },
    {
        "name": "Wasp",
        "wiki_page": "https://en.wikipedia.org/wiki/Wasp",
        "fun_fact": "Builds nests from chewed wood",
        "home": ["in forests", "in grasslands"],
        "food": ["Nectar", "Meat"],
        "alt_name": "Wasp",
        "group": "Invertebrate",
        "colors": ["Yellow", "Black"],
        "size": "Very Tiny",
        "movement": "Wings",
        "sound": "Buzzes"
    },
    {
        "name": "Falcon",
        "wiki_page": "https://en.wikipedia.org/wiki/Falcon",
        "fun_fact": "Fastest bird, dives at 200 mph",
        "home": ["on mountains", "in grasslands"],
        "food": ["Meat"],
        "alt_name": "Falcon",
        "group": "Bird",
        "colors": ["Brown", "Gray"],
        "size": "Medium",
        "movement": "Wings",
        "sound": "Screeches"
    },
    {
        "name": "Salamander",
        "wiki_page": "https://en.wikipedia.org/wiki/Salamander",
        "fun_fact": "Can regrow lost limbs",
        "home": ["in wetlands", "in forests"],
        "food": ["Meat"],
        "alt_name": "Salamander",
        "group": "Amphibian",
        "colors": ["Black", "Yellow"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Quiet"
    },
    {
        "name": "Humpback Whale",
        "wiki_page": "https://en.wikipedia.org/wiki/Humpback_whale",
        "fun_fact": "Sings long, beautiful songs",
        "home": ["in oceans"],
        "food": ["Plankton", "Meat"],
        "alt_name": "Humpback Whale",
        "group": "Mammal",
        "colors": ["Black", "White"],
        "size": "Huge",
        "movement": "Fins",
        "sound": "Sings"
    },
    {
        "name": "Beluga Whale",
        "wiki_page": "https://en.wikipedia.org/wiki/Beluga_whale",
        "fun_fact": "Called sea canary for its chirps",
        "home": ["in oceans", "in snowy areas"],
        "food": ["Meat"],
        "alt_name": "Beluga Whale",
        "group": "Mammal",
        "colors": ["White"],
        "size": "Big",
        "movement": "Fins",
        "sound": "Chirps"
    },
    {
        "name": "Angelfish",
        "wiki_page": "https://en.wikipedia.org/wiki/Pterophyllum",
        "fun_fact": "Has bright colors to blend with coral",
        "home": ["in oceans"],
        "food": ["Plants", "Meat"],
        "alt_name": "Angelfish",
        "group": "Fish",
        "colors": ["Yellow", "Black"],
        "size": "Small",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Squid",
        "wiki_page": "https://en.wikipedia.org/wiki/Squid",
        "fun_fact": "Squirts ink to escape predators",
        "home": ["in oceans"],
        "food": ["Meat"],
        "alt_name": "Squid",
        "group": "Invertebrate",
        "colors": ["Red", "White"],
        "size": "Medium",
        "movement": "Fins",
        "sound": "Quiet"
    },
    {
        "name": "Elk",
        "wiki_page": "https://en.wikipedia.org/wiki/Elk",
        "fun_fact": "Has antlers that grow every year",
        "home": ["in forests", "on mountains"],
        "food": ["Plants"],
        "alt_name": "Elk",
        "group": "Mammal",
        "colors": ["Brown"],
        "size": "Big",
        "movement": "4 Legs",
        "sound": "Bugles"
    },
    {
        "name": "Armadillo",
        "wiki_page": "https://en.wikipedia.org/wiki/Armadillo",
        "fun_fact": "Has armor-like skin for protection",
        "home": ["in grasslands", "in forests"],
        "food": ["Meat"],
        "alt_name": "Armadillo",
        "group": "Mammal",
        "colors": ["Gray", "Brown"],
        "size": "Medium",
        "movement": "4 Legs",
        "sound": "Grunts"
    },
    {
        "name": "Tree Frog",
        "wiki_page": "https://en.wikipedia.org/wiki/Tree_frog",
        "fun_fact": "Has sticky toes for climbing trees",
        "home": ["in jungles", "in wetlands"],
        "food": ["Meat"],
        "alt_name": "Tree Frog",
        "group": "Amphibian",
        "colors": ["Green", "Red"],
        "size": "Tiny",
        "movement": "4 Legs",
        "sound": "Croaks"
    },
    {
        "name": "Axolotl",
        "wiki_page": "https://en.wikipedia.org/wiki/Axolotl",
        "fun_fact": "Can regrow its arms and legs",
        "home": ["in wetlands"],
        "food": ["Meat"],
        "alt_name": "Axolotl",
        "group": "Amphibian",
        "colors": ["Pink", "Brown"],
        "size": "Small",
        "movement": "4 Legs",
        "sound": "Quiet"
    }
];